ViewComponents/MenuAccountViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WeShare.Web;

namespace First.ViewComponents
{
    public class MenuAccountViewComponent : ViewComponent
    {

        protected AppDbContext Context;
        protected UserManager<ApplicationUser> UserManager;
        protected SignInManager<ApplicationUser> SignInManager;

        public MenuAccountViewComponent(
            AppDbContext context,
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            Context = context;
            UserManager = userManager;
            SignInManager = signInManager;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {   
            ApplicationUser user = null;
            if(SignInManager.IsSignedIn(HttpContext.User)) {
                user = await UserManager.GetUserAsync(HttpContext.User);
                return View("Default", user);
            }
            else{return View("Default", user);}
        }
    }
}

ViewComponents/MenuNotificationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace First.ViewComponents
{
    public class MenuNotificationViewComponent : ViewComponent
    {

        public MenuNotificationViewComponent()
        {
        }

        public IViewComponentResult Invoke(
        int maxPriority, bool isDone)
        {
            string items = "Ok";
            return View("Default", items);
        }
      
    }
}

ViewComponents/SearchVideoBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace First.ViewComponents
{
    public class SearchVideoBarViewComponent : ViewComponent
    {

        public SearchVideoBarViewComponent()
        {
        }

        public IViewComponentResult Invoke(
        int maxPriority, bool isDone)
        {
            string items = "Ok";
            return View("Default", items);
        }
      
    }
}

Views/Shared/menuLateral.cshtml
 <aside id="menuLateral">
    <a href="#" class="item active inicio">
        <div class="icone">
            <i class="fas fa-home"></i>
        </div>
        <div class="desc">Inicio</div>
    </a>
    <a href="#" class="item alta">
        <div class="icone">
            <i class="fas fa-fire"></i>
        </div>
        <div class="desc dw">Em Alta</div>
    </a>
    <a href="#" class="item subindo">
        <div class="icone">
            <i class="fas fa-chart-line"></i>
        </div>
        <div class="desc">Subindo</div>
    </a>
    <a href="#" class="item novo">
        <div class="icone">
            <i class="far fa-clock"></i>
        </div>
        <div class="desc">Novo</div>
    </a>
    <a id="btnSubscriptions" href="#" class="item canais active">
        <div class="icone">
            <i class="fas fa-star"></i>
        </div>
        <div class="desc">Inscrições</div>
        <button class="expand">
            <i class="fa fa-angle-up"></i>
            <i class="fa fa-angle-down" style="display:none;"></i>
        </button>
    </a>
    <div id="subscriptions" class="canais">
        <a href="#" class="canal">
            <div class="icone">
                <img src="~/img/nilce.jpg" alt="Cade a Chave">
                
            </div>
            <div class="desc">Cade a chave</div>
            <div class="warning"></div>
        </a>
        <a href="#" class="canal active">
            <div class="icone">
                <img src="~/img/testeconta.jpg" alt="Elon Musk">
            </div>
            <div class="desc">Elon Musk</div>
        </a>
        <a href="#" class="canal">
            <div class="icone">
                <img src="~/img/cellbit.jpg" alt="Elon Musk">
            </div>
            <div class="desc">Cellbit</div>
        </a>
    </div>
    <a id="btnComunidades" href="#" class="item comunidades">
        <div class="icone">
            <i class="far fa-smile"></i>
        </div>
        <div class="desc">Comunidades</div>
        <button class="expand">
            <i class="fa fa-angle-up" style="display: none;"></i>
            <i class="fa fa-angle-down"></i>
        </button>
    </a>
    <div id="comunidades" class="comunidades">
        <a href="#" class="comunidade">
            <div class="icone">
                <img src="~/img/ancap.jpg" alt="Ancaps">
            </div>
            <div class="desc">Cultura Libertária</div>
        </a>
        <a href="#" class="comunidade">
            <div class="icone">
                <img src="~/img/anime.jpg" alt="Animes">
            </div>
            <div class="desc">Animes</div>
        </a>
        <a href="#" class="comunidade active">
            <div class="icone">
                <img src="~/img/indie.png" alt="Indie">
            </div>
            <div class="desc">Músicas Indie</div>
        </a>
    </div>
    <footer>
        <button id="btnToggleMenu">
            <i class="fa fa-angle-left"></i>
            <i class="fa fa-angle-right" style="display:none"></i>
        </button>
    </footer>
    <div id="rodape3" style="display:none;">
        <p id="copyright">WeShare -
            <span id="year">2019
                <img src="" width="60"/>
            </span>
        </p>
    </div>
</aside>

Views/Shared/menuTop.cshtml
<header>
    <nav id="menutop" class="p2">
        <button id="btnExpandir" data-tooltip="Menu"><i class="fas fa-bars"></i></button>
        <img id="logo" src="~/img/logo.png" alt="WeShare">
        @await Component.InvokeAsync("SearchVideoBar", new { maxPriority = 2, isDone = false })
        <div class="info">
            <button class="btn" id="upload">
                <i class="fas fa-arrow-circle-up"></i>
                <span class="text">Upload</span>
            </button>
            @await Component.InvokeAsync("MenuNotification", new { maxPriority = 2, isDone = false })
            @await Component.InvokeAsync("MenuAccount")
        </div>
    </nav>
</header>